apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
    spec:
      containers:
      - image: docker.io/bitnami/zookeeper:3-debian-10
        name: zookeeper
        env:
          - name: "ALLOW_ANONYMOUS_LOGIN"
            value: "yes"
      - image: docker.io/bitnami/kafka:2-debian-10
        name: kafka
        env:
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: "localhost:2181"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"